# Generated by Django 4.2 on 2025-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
