# Generated by Django 4.2 on 2025-08-24 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taux_quotidien',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=5, verbose_name='Taux quotidien'),
        ),
    ]
