# Generated by Django 4.2 on 2025-08-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('gain_quotidien', 'Gain quotidien'), ('bonus_parrainage', 'Bonus parrainage'), ('achat', 'Achat marchandise')], max_length=24, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='Référence')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après transaction')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
