# Generated by Django 4.2 on 2025-08-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant du bonus')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('depot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paiements.depot', verbose_name='Dépôt associé')),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrain', to=settings.AUTH_USER_MODEL, verbose_name='Filleul')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrainages', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
            ],
        ),
    ]
