# Generated by Django 4.2 on 2025-08-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('methode', models.CharField(max_length=32, verbose_name='Méthode de retrait')),
                ('destination', models.CharField(max_length=128, verbose_name='Destination (numéro de compte/téléphone)')),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('en_traitement', 'En traitement'), ('paye', 'Payé'), ('rejete', 'Rejeté')], default='demande', max_length=13, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('methode', models.CharField(max_length=32, verbose_name='Méthode de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('rejete', 'Rejeté')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Référence')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('confirme_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
