# Generated by Django 4.2 on 2025-08-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='confirme_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='methode',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='depot',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='depot',
            name='reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('rejete', 'Rejeté')], default='confirme', max_length=12),
        ),
        migrations.AlterField(
            model_name='depot',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to=settings.AUTH_USER_MODEL),
        ),
    ]
