# Generated by Django 4.2 on 2025-08-18 15:11


from django.db import migrations
from django.utils import timezone

def update_confirme_le(apps, schema_editor):
    Depot = apps.get_model('paiements', 'Depot')
    for depot in Depot.objects.filter(confirme_le__isnull=True, statut='confirme'):
        depot.confirme_le = timezone.now()
        depot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_alter_depot_confirme_le_alter_depot_cree_le_and_more'),  # Remplacez par la dernière migration
    ]

    operations = [
        migrations.RunPython(update_confirme_le),
    ]

