# Generated by Django 4.2 on 2025-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_update_confirme_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='confirme_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
